name: Publish

on:
  push:

jobs:
  publish-prerelease:
    name: "Publish Pre-Release"
    runs-on: [ubuntu-latest]
    steps:
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Make path
        shell: bash
        run: mkdir -p bin/x64/plugins/cyber_engine_tweaks/mods

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: bin/x64/plugins/cyber_engine_tweaks/mods

      - name: Make archive
        shell: bash
        run: 7z a -xr'!.*' -tzip SimpleUtils.zip bin

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
          name: SimpleUtils ${{ steps.vars.outputs.sha_short }}
          artifacts: "SimpleUtils.zip"
          prerelease: true