name: Publish

on:
  push:

jobs:
  publish-prerelease:
    name: "Publish Pre-Release"
    runs-on: [ubuntu-latest]
    steps:
      - name: Make path
        shell: bash
        run: mkdir -p bin/x64/plugins/cyber_engine_tweaks/mods

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: bin/x64/plugins/cyber_engine_tweaks/mods

      - name: Make archive
        shell: bash
        run: 7z a -tzip SimpleUtils.zip bin

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}-${{ github.sha }}
          name: SimpleUtils ${{ github.sha }}
          artifacts: "SimpleUtils.zip"
          prerelease: true